// Active NWS alerts limited to what the radar actually shows, so a watch in
// Maine doesn't clutter the list. Same no-key, CORS-friendly API as nws.ts.
//
// The radar card covers roughly 36-46N, 102.4W-85.1W (derived from the
// iframe's zoom level and native size; padded a few tenths of a degree). NWS
// has no bounding-box alert query, so this asks for the states that overlap
// that box and then filters precisely:
//   - Alerts with a polygon (tornado/severe thunderstorm/flash flood
//     warnings): NWS issues these for the threatened storm area, not whole
//     counties, so the polygon itself is used.
//   - Everything else (watches, advisories, most other warnings) is issued
//     for a list of counties/forecast zones. Their outlines come from
//     public/data/zones.json (generated by scripts/build-zone-outlines.mjs),
//     so the alert is drawn as the actual counties it covers.

// Where an alert applies, for drawing on the map: one or more closed outlines
// of [lon, lat] points.
export interface AlertShape {
  rings: [number, number][][];
}

export interface MapAlert {
  id: string;
  event: string;
  headline: string | null;
  description: string;
  severity: string;
  areaDesc: string;
  expires: string | null;
  /** NWS's "what to do" text, when the alert has any. */
  instruction: string | null;
  /** Issuing office, e.g. "NWS Des Moines IA". */
  senderName: string | null;
  shapes: AlertShape[];
}

const BOX = { south: 35.6, north: 46.1, west: -102.7, east: -84.8 };

// States that overlap the box at all.
const STATES = [
  "SD", "NE", "KS", "OK", "MN", "IA", "MO", "AR", "WI", "IL", "IN", "KY", "TN", "MI", "CO", "TX", "NM",
];

interface AlertFeature {
  geometry: GeoJsonGeometry | null;
  properties: {
    id: string;
    event: string;
    headline: string | null;
    description: string;
    severity: string;
    areaDesc: string;
    expires: string | null;
    ends: string | null;
    messageType: string;
    affectedZones: string[];
    instruction: string | null;
    senderName: string | null;
  };
}

type Position = number[];
type GeoJsonGeometry =
  | { type: "Polygon"; coordinates: Position[][] }
  | { type: "MultiPolygon"; coordinates: Position[][][] }
  | { type: "GeometryCollection"; geometries: GeoJsonGeometry[] };

async function getJson<T>(url: string): Promise<T> {
  const res = await fetch(url, { headers: { Accept: "application/geo+json" } });
  if (!res.ok) throw new Error(`NWS request failed: ${res.status} ${res.statusText}`);
  return res.json() as Promise<T>;
}

function rings(geometry: GeoJsonGeometry): Position[][] {
  switch (geometry.type) {
    case "Polygon":
      return geometry.coordinates ?? [];
    case "MultiPolygon":
      return (geometry.coordinates ?? []).flat();
    case "GeometryCollection":
      return (geometry.geometries ?? []).flatMap(rings);
    default:
      return [];
  }
}

// Does this set of outlines' bounding rectangle overlap the radar box?
function overlapsBox(outlines: Position[][]): boolean {
  let minLon = Infinity;
  let maxLon = -Infinity;
  let minLat = Infinity;
  let maxLat = -Infinity;
  for (const ring of outlines) {
    for (const [lon, lat] of ring) {
      minLon = Math.min(minLon, lon);
      maxLon = Math.max(maxLon, lon);
      minLat = Math.min(minLat, lat);
      maxLat = Math.max(maxLat, lat);
    }
  }
  return minLon <= BOX.east && maxLon >= BOX.west && minLat <= BOX.north && maxLat >= BOX.south;
}

// ---- Zone outlines (counties and forecast zones), loaded once.

type ZoneTable = Record<string, number[][]>; // code -> rings of flat [lon*100, lat*100, ...]

let zoneTable: Promise<ZoneTable> | null = null;

function loadZones(): Promise<ZoneTable> {
  if (!zoneTable) {
    zoneTable = fetch(`${import.meta.env.BASE_URL}data/zones.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`zones.json ${res.status}`);
        return res.json() as Promise<ZoneTable>;
      })
      .catch(() => {
        zoneTable = null; // try again on the next refresh
        return {} as ZoneTable;
      });
  }
  return zoneTable;
}

function decodeRing(flat: number[]): [number, number][] {
  const points: [number, number][] = [];
  for (let i = 0; i + 1 < flat.length; i += 2) points.push([flat[i] / 100, flat[i + 1] / 100]);
  return points;
}

// "https://api.weather.gov/zones/county/IAC153" -> "IAC153"
const zoneCode = (url: string) => url.split("/").pop() ?? "";

const SEVERITY_RANK: Record<string, number> = { Extreme: 4, Severe: 3, Moderate: 2, Minor: 1 };

export async function fetchMapAlerts(): Promise<MapAlert[]> {
  const [data, zones] = await Promise.all([
    getJson<{ features: AlertFeature[] }>(
      `https://api.weather.gov/alerts/active?status=actual&area=${STATES.join(",")}`
    ),
    loadZones(),
  ]);

  const now = Date.now();
  const alerts: MapAlert[] = [];
  for (const f of data.features) {
    const p = f.properties;
    if (p.messageType === "Cancel") continue;
    const end = p.ends ?? p.expires;
    if (end && new Date(end).getTime() <= now) continue;

    let shapes: AlertShape[];
    if (f.geometry) {
      const outline = rings(f.geometry);
      if (!overlapsBox(outline)) continue;
      shapes = [
        { rings: outline.map((r) => r.map(([lon, lat]) => [Math.round(lon * 1000) / 1000, Math.round(lat * 1000) / 1000] as [number, number])) },
      ];
    } else {
      // Zone-based: keep the counties/zones that touch the radar's area.
      const covered: [number, number][][] = [];
      for (const url of p.affectedZones ?? []) {
        const zone = zones[zoneCode(url)];
        if (!zone) continue;
        const decoded = zone.map(decodeRing);
        if (overlapsBox(decoded)) covered.push(...decoded);
      }
      if (covered.length === 0) continue;
      shapes = [{ rings: covered }];
    }

    alerts.push({
      id: p.id,
      event: p.event,
      headline: p.headline,
      description: p.description,
      severity: p.severity,
      areaDesc: p.areaDesc,
      expires: end,
      instruction: p.instruction ?? null,
      senderName: p.senderName ?? null,
      shapes,
    });
  }

  return alerts.sort(
    (a, b) => (SEVERITY_RANK[b.severity] ?? 0) - (SEVERITY_RANK[a.severity] ?? 0) || a.event.localeCompare(b.event)
  );
}
