// Every active NWS alert in the country, ready to draw on the radar. Same
// no-key, CORS-friendly API as nws.ts. The page shows only the alerts that
// overlap the part of the map being looked at (see alertsInBounds), so a
// visitor in Iowa can pan to Arizona or Oregon and see what is happening there.
//
//   - Alerts with a polygon (tornado/severe thunderstorm/flash flood
//     warnings and most river flood warnings): NWS issues these for the
//     threatened area, not whole counties, so the polygon itself is used.
//   - Everything else (watches, advisories, most other warnings) is issued
//     for a list of counties/forecast zones. Their outlines come from
//     public/data/zones.json (generated by scripts/build-zone-outlines.mjs),
//     so the alert is drawn as the actual counties it covers. Marine-zone
//     alerts have no entries there and are left out.

// Where an alert applies, for drawing on the map: one or more closed outlines
// of [lon, lat] points.
export interface AlertShape {
  rings: [number, number][][];
}

export interface Bounds {
  west: number;
  south: number;
  east: number;
  north: number;
}

export interface MapAlert {
  id: string;
  event: string;
  headline: string | null;
  description: string;
  severity: string;
  areaDesc: string;
  expires: string | null;
  /** NWS's "what to do" text, when the alert has any. */
  instruction: string | null;
  /** Issuing office, e.g. "NWS Des Moines IA". */
  senderName: string | null;
  shapes: AlertShape[];
  /** Extent of all shapes, for quick "is it on screen" checks. */
  bounds: Bounds;
}

interface AlertFeature {
  geometry: GeoJsonGeometry | null;
  properties: {
    id: string;
    event: string;
    headline: string | null;
    description: string;
    severity: string;
    areaDesc: string;
    expires: string | null;
    ends: string | null;
    messageType: string;
    affectedZones: string[];
    instruction: string | null;
    senderName: string | null;
  };
}

type Position = number[];
type GeoJsonGeometry =
  | { type: "Polygon"; coordinates: Position[][] }
  | { type: "MultiPolygon"; coordinates: Position[][][] }
  | { type: "GeometryCollection"; geometries: GeoJsonGeometry[] };

async function getJson<T>(url: string): Promise<T> {
  const res = await fetch(url, { headers: { Accept: "application/geo+json" } });
  if (!res.ok) throw new Error(`NWS request failed: ${res.status} ${res.statusText}`);
  return res.json() as Promise<T>;
}

function rings(geometry: GeoJsonGeometry): Position[][] {
  switch (geometry.type) {
    case "Polygon":
      return geometry.coordinates ?? [];
    case "MultiPolygon":
      return (geometry.coordinates ?? []).flat();
    case "GeometryCollection":
      return (geometry.geometries ?? []).flatMap(rings);
    default:
      return [];
  }
}

function boundsOf(outlines: Position[][]): Bounds | null {
  let west = Infinity;
  let east = -Infinity;
  let south = Infinity;
  let north = -Infinity;
  for (const ring of outlines) {
    for (const [lon, lat] of ring) {
      if (lon < west) west = lon;
      if (lon > east) east = lon;
      if (lat < south) south = lat;
      if (lat > north) north = lat;
    }
  }
  return Number.isFinite(west) ? { west, south, east, north } : null;
}

// Alerts whose extent overlaps the given map bounds.
export function alertsInBounds(alerts: MapAlert[], view: Bounds): MapAlert[] {
  return alerts.filter(
    (a) => a.bounds.west <= view.east && a.bounds.east >= view.west && a.bounds.south <= view.north && a.bounds.north >= view.south
  );
}

// ---- Zone outlines (counties and forecast zones), loaded once.

type ZoneTable = Record<string, number[][]>; // code -> rings of flat [lon*100, lat*100, ...]

let zoneTable: Promise<ZoneTable> | null = null;

function loadZones(): Promise<ZoneTable> {
  if (!zoneTable) {
    zoneTable = fetch(`${import.meta.env.BASE_URL}data/zones.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`zones.json ${res.status}`);
        return res.json() as Promise<ZoneTable>;
      })
      .catch(() => {
        zoneTable = null; // try again on the next refresh
        return {} as ZoneTable;
      });
  }
  return zoneTable;
}

function decodeRing(flat: number[]): [number, number][] {
  const points: [number, number][] = [];
  for (let i = 0; i + 1 < flat.length; i += 2) points.push([flat[i] / 100, flat[i + 1] / 100]);
  return points;
}

// "https://api.weather.gov/zones/county/IAC153" -> "IAC153"
const zoneCode = (url: string) => url.split("/").pop() ?? "";

const SEVERITY_RANK: Record<string, number> = { Extreme: 4, Severe: 3, Moderate: 2, Minor: 1 };

export async function fetchMapAlerts(): Promise<MapAlert[]> {
  const [data, zones] = await Promise.all([
    getJson<{ features: AlertFeature[] }>("https://api.weather.gov/alerts/active?status=actual"),
    loadZones(),
  ]);

  const now = Date.now();
  const alerts: MapAlert[] = [];
  for (const f of data.features) {
    const p = f.properties;
    if (p.messageType === "Cancel") continue;
    const end = p.ends ?? p.expires;
    if (end && new Date(end).getTime() <= now) continue;

    let outlines: [number, number][][];
    if (f.geometry) {
      outlines = rings(f.geometry).map((r) =>
        r.map(([lon, lat]) => [Math.round(lon * 1000) / 1000, Math.round(lat * 1000) / 1000] as [number, number])
      );
    } else {
      // Zone-based: the counties/zones the alert was issued for.
      outlines = [];
      for (const url of p.affectedZones ?? []) {
        const zone = zones[zoneCode(url)];
        if (zone) outlines.push(...zone.map(decodeRing));
      }
    }
    const bounds = boundsOf(outlines);
    if (!bounds) continue;

    alerts.push({
      id: p.id,
      event: p.event,
      headline: p.headline,
      description: p.description,
      severity: p.severity,
      areaDesc: p.areaDesc,
      expires: end,
      instruction: p.instruction ?? null,
      senderName: p.senderName ?? null,
      shapes: [{ rings: outlines }],
      bounds,
    });
  }

  return alerts.sort(
    (a, b) => (SEVERITY_RANK[b.severity] ?? 0) - (SEVERITY_RANK[a.severity] ?? 0) || a.event.localeCompare(b.event)
  );
}
